### ISSUE TITLE
[SR-15370] REPL: messed up readline support even without resizing windows

### ISSUE THREAD

**Issue by weissi** [swiftlang/llvm-project#4302]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15370      |
   |Radar             | rdar://problem/84518637         |
   |Original Reporter | @weissi      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, Linux        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 75e4034b984641fc0d77ced822e04b2d

  </details>

**Issue Description:**

In the below REPL session I typed

-   `import Foundation`

-   `Host.current`

-   up arrow

what is shown is

    Welcome to Swift version 5.5 (swift-5.5-RELEASE).
    Type :help for assistance.
      1> import Foundation
      2> Host.current
    $R0: () -> Host =
      3> currentrrent 

See that line 3 says `currentrrent` instead of `Host.current`. It's only the display that's messed up. If you press Enter, it works.

**Comment by weissi** [comment]
@swift-ci create

**Comment by weissi** [comment]
CC @adrian-prantl

**Comment by mickeyl** [comment]
Which platform is this on? Might be related to <https://bugs.swift.org/browse/SR-15485>

**Comment by weissi** [comment]
@mickeyl This is Linux too

**Comment by augusto2112** [comment]
Duplicate of <https://bugs.swift.org/browse/SR-15369.>

I'm marking these as dups so we can concentrate the discussion on a single issue. It has been fixed on main for a while, but unfortunately i missed the window to cherry-pick it into 5.5. If you're able to, please download the main snapshot on [https://www.swift.org/download/,](https://www.swift.org/download/) verify if it's working for you and letting me know on the SR-15369.

**Comment by weissi** [comment]
Yes, this is fixed. Thank you!

**Comment by weissi** [comment]
`Swift version 5.6-dev (LLVM c8e0f2fe28693ea, Swift 68eb340a2b7690f).` works
