### ISSUE TITLE
[SR-15369] REPL: After `import Something`, colons don't show anymore

### ISSUE THREAD

**Issue by weissi** [swiftlang/llvm-project#4303]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15369      |
   |Radar             | rdar://problem/84518632         |
   |Original Reporter | @weissi      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, Linux        |
   |Assignee          | @augusto2112      |
   |Priority          | Medium      |

   

   md5: ddccf9f7591a24b3c6d364b1cab0d229

  </details>

**Issue Description:**

this is on Linux, 5.5 RELEASE

    Welcome to Swift version 5.5 (swift-5.5-RELEASE).
    Type :help for assistance.
      1> ::::: # 5 colons to the left
    error: '::::' is not a valid command.
      1> import Dispatch
      2>       # 5 colons to the left
    error: '::::' is not a valid command.
      2>

**Comment by weissi** [comment]
@swift-ci create

**Comment by weissi** [comment]
CC @adrian-prantl

**Comment by augusto2112** [comment]
svanimpe (JIRA User) this is indeed the same issue. It has been fixed on main for a while, but unfortunately i missed the window to cherry-pick it into 5.5. Steven or @weissi could you download the main snapshot on <https://www.swift.org/download/> and verify if it's working for you?

**Comment by xwu** [comment]
What’s the link to the PR?

**Comment by augusto2112** [comment]
@xwu this was fixed here: https://reviews.llvm.org/D95230

**Comment by weissi** [comment]
@augusto2112 Thank you, I can confirm this is fixed

    Welcome to Swift version 5.6-dev (LLVM c8e0f2fe28693ea, Swift 68eb340a2b7690f).
    Type :help for assistance.
      1> :::::
    error: '::::' is not a valid command.
      1> import Dispatch
      2> :::::

**Comment by augusto2112** [comment]
Unfortunately, only on 5.6. There are already 5.6 snapshots available on <https://www.swift.org/download/> if you'd like to get the fix now.
