### ISSUE TITLE
[SR-15127] LLDB's TypeSystemSwiftTypeRef::GetEncoding() assertion fails on many common types

### ISSUE THREAD

**Issue by BradLarson** [swiftlang/llvm-project#4306]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15127      |
   |Radar             | rdar://problem/82537719         |
   |Original Reporter | @BradLarson      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: fc3759b70fe42c89371a809dd0a9e6c8

  </details>

**Issue Description:**

In builds with assertions enabled (such as the nightly macOS Swift toolchains), LLDB regularly hits an assertion failure in TypeSystemSwiftTypeRef::GetEncoding() when printing variables in many common cases. For example, if you create the following file in Xcode:

``` swift
import Dispatch

public enum MyEnum {
    case good
    case bad
}

public extension DispatchQueue {
    func asyncEC(
        test: MyEnum = .good,
        execute work: @escaping () -> Void
    ) {
        self.async(execute: work)
    }
}

let queue = DispatchQueue(label: "A", attributes: .concurrent)

queue.asyncEC {
    let a = 33
    print(a)
}
```

and set a breakpoint on the \`self.async()\` line, building and running the above will lead to an lldb-rpc-server crash due to the failing assertion [here](https://github.com/apple/llvm-project/blob/next/lldb/source/Plugins/TypeSystem/Swift/TypeSystemSwiftTypeRef.cpp#L2283). This renders LLDB unusable within Xcode when working with the nightly Swift snapshots and placing breakpoints in areas that trigger this assertion.

The assertion appears to be the result of non-builtin types (such as the MyEnum type above) falling through the switch statement there. The previous implementation of TypeSystemSwiftTypeRef::GetEncoding() (replaced in [this commit](https://github.com/apple/llvm-project/commit/46ec3ba02b03cd95dcf45f1589a6de68aec6d538)) simply called [SwiftASTContext's getEncoding()](https://github.com/apple/llvm-project/blob/next/lldb/source/Plugins/TypeSystem/Swift/SwiftASTContext.cpp#L6136) which did not have an assertion for types that fell through the switch statement in the same way. It returned a value of \`lldb::eEncodingInvalid\` for many of those types.

If you remove the assertion on line 2283 in TypeSystemSwiftTypeRef::GetEncoding() and build a toolchain with that version of LLDB within it, lldb-rpc-server no longer crashes in Xcode in the same places and appears to behave properly. However, simply pulling out an assertion is usually not a preferred solution, so there may be a better way to resolve this.

**Comment by typesanitizer** [comment]
cc @kastiglione

@swift-ci create

**Comment by adrian-prantl** [comment]
doesn't reproduce on rebranch.

**Comment by adrian-prantl** [comment]
I can't reproduce this on release/5.5 either:

\`\`\`

(lldb) v

(a.MyEnum) test = good

\`\`\`

**Comment by adrian-prantl** [comment]
Maybe it's about a specific query Xcode makes. I'll try a downloadable toolchain.

**Comment by adrian-prantl** [comment]
GetEncoding: Unhandled node kind for type $s9asynctest6MyEnumOD

**Comment by adrian-prantl** [comment]
<https://github.com/apple/llvm-project/pull/3241>

**Comment by adrian-prantl** [comment]
Thanks for reporting this and particularly thanks for the test case!

**Comment by BradLarson** [comment]
@adrian-prantl - Thanks for the quick fix, that'll greatly improve the development experience for folks on our end. Sorry about not specifying that we only observed this in Xcode.
