### ISSUE TITLE
[SR-14845] REPL does not support "-debug-diagnostic-names"

### ISSUE THREAD

**Issue by beccadax** [swiftlang/llvm-project#4308]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14845      |
   |Radar             | rdar://problem/79920539         |
   |Original Reporter | @beccadax      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | @poya      |
   |Priority          | Medium      |

   

   md5: 594e66cefcdfa17e3ea8a744d4875b1e

  </details>

**Issue Description:**

``` none
$ swift -debug-diagnostic-names
Welcome to Apple Swift version 5.5
Type :help for assistance.
  1> }
error: repl.swift:1:1: error: extraneous '}' at top level
}
^
```

I would expect to see `[extra_rbrace]` at the end of that diagnostic.

**Comment by typesanitizer** [comment]
@swift-ci create

**Comment by poya** [comment]
Support added in <https://github.com/apple/llvm-project/pull/3210>
