### ISSUE TITLE
[SR-13804] REPL crashes on Windows

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4328]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13804      |
   |Radar             | None         |
   |Original Reporter | svanimpe (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

29/10 snapshot on Windows.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, Windows        |
   |Assignee          | @compnerd      |
   |Priority          | Medium      |

   

   md5: b392d0f7e4ff7f83113cf198247d86c1

  </details>

**duplicates**:  
* [SR-13591](https://bugs.swift.org/browse/SR-13591) REPL is not working on swift-5.3-RELEASE (Windows)  

**is duplicated by**:  
* [SR-13805](https://bugs.swift.org/browse/SR-13805) Running source files with REPL not working on Windows  

**Issue Description:**

With the 29/10 snapshot and these commands:

``` java
path %ProgramFiles(x86)%\Microsoft Visual Studio\Shared\Python37_64;%PATH%
set SWIFTFLAGS=-sdk %SDKROOT% -I %SDKROOT%/usr/lib/swift -L SDKROOT%/usr/lib/swift/windows
swift repl -target x86_64-unknown-windows-msvc %SWIFTFLAGS%
```

I can start the REPL, but it crashes as soon as I evaluate an expression:

    Welcome to compnerd.org Swift version 5.3-dev (LLVM 6df6611ced20c9f, Swift 142b7267089e96d).
    Type :help for assistance.
    1> 1+1
    Assertion failed: false && "called into swift language runtime stub", file D:\a\1\s\llvm-project\lldb\source\Target\SwiftLanguageRuntime.cpp, line 301
    PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
    error: reproducer finalization failed: unable to load reproducer index
     #&#8203;0 0x00007ff7e2eed735 (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\lldb.exe+0x1d735)
     #&#8203;1 0x00007ffacea9caad (C:\WINDOWS\System32\ucrtbase.dll+0x6caad)
     #&#8203;2 0x00007ffacea9dab1 (C:\WINDOWS\System32\ucrtbase.dll+0x6dab1)
     #&#8203;3 0x00007ffacea9f4ee (C:\WINDOWS\System32\ucrtbase.dll+0x6f4ee)
     #&#8203;4 0x00007ffacea9f3e5 (C:\WINDOWS\System32\ucrtbase.dll+0x6f3e5)
     #&#8203;5 0x00007ffacea9f771 (C:\WINDOWS\System32\ucrtbase.dll+0x6f771)
     #&#8203;6 0x00007ffa765432fc PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x6732fc)
     #&#8203;7 0x00007ffa7ae2e5c4 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x4f5e5c4)
     #&#8203;8 0x00007ffa7ae33fa6 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x4f63fa6)
     #&#8203;9 0x00007ffa7ae31776 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x4f61776)
    #&#8203;10 0x00007ffa7ae2be44 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x4f5be44)
    #&#8203;11 0x00007ffa763ef857 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x51f857)
    #&#8203;12 0x00007ffa763fdce7 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x52dce7)
    #&#8203;13 0x00007ffa763ca3ac PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x4fa3ac)
    #&#8203;14 0x00007ffa7637a6e9 PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x4aa6e9)
    #&#8203;15 0x00007ffa7637931e PyInit__lldb (C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\liblldb.dll+0x4a931e)
    #&#8203;16 0x00007ffacea510b2 (C:\WINDOWS\System32\ucrtbase.dll+0x210b2)
    #&#8203;17 0x00007ffad0397c24 (C:\WINDOWS\System32\KERNEL32.DLL+0x17c24)
    #&#8203;18 0x00007ffad0c8cea1 (C:\WINDOWS\SYSTEM32\ntdll.dll+0x6cea1)

**Comment by compnerd** [comment]
+@JDevlieghere @kastiglione

Perhaps either Jonas or Dave have ideas off the top of their heads why the REPL environment is loosing the \`Path\` environment variable, which prevents dependent libraries from being found when \`LoadLibraryW\` is being invoked to map in libraries.
