### ISSUE TITLE
[SR-13754] Failure in SwiftREPL/RedirectInput.test on Linux

### ISSUE THREAD

**Issue by benrimmington** [swiftlang/llvm-project#4329]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13754      |
   |Radar             | rdar://problem/70531607         |
   |Original Reporter | @benrimmington      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963992-43da7922-aad2-48e3-a5fc-f1adf4c04ae1.gz)

      
<details>
  <summary>Environment</summary>

Ubuntu 16.04.6 LTS

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3bcdb2e6857236b3f3e64a9991ccce83

  </details>

**Issue Description:**

There was a failure in `lldb-shell :: SwiftREPL/RedirectInput.test` on Linux.

I can see the files in my working copy, but I can't find them on [GitHub](https://github.com/apple/llvm-project/tree/apple/main/lldb/test/Shell).

The `llvm-project/lldb/test/Shell/SwiftREPL/RedirectInput.test` file contains:

``` Swift
Foo.foo()
// CHECK: ${{R0}}: String = "A"
```

The `llvm-project/lldb/test/Shell/SwiftREPL/Inputs/A.swift` file contains:

``` Swift
public class Foo {
  public static func foo() -> String  {
    print("A")
    return "A"
  }
}
```

The expected REPL output is intermixed with the `print("A")` output:

    $R0: String =A
     "A"

I've attached the relevant part of the consoleText file from Swift CI.

**Comment by typesanitizer** [comment]
@swift-ci create

**Comment by adrian-prantl** [comment]
<https://github.com/apple/llvm-project/pull/2023>
