### ISSUE TITLE
[SR-11238] Swift REPL: Cannot use custom operators

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4331]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11238      |
   |Radar             | rdar://problem/53764712         |
   |Original Reporter | palle (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Won't Do    |
        
<details>
  <summary>Environment</summary>

Swift version 5.1 (swiftlang-1100.0.266.1 clang-1100.0.32.1)

Xcode 11.0 beta 5 (11M382q)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | palle (JIRA)      |
   |Priority          | Medium      |

   

   md5: 2e2d01366b8623d39ed240c9b4a45bc9

  </details>

**Issue Description:**

When the user declares a custom operator in the REPL, the operator is not defined in subsequent statements.

 

Steps to reproduce:

1.  Open a terminal

2.  Type in `swift` and press return to start the REPL

3.  Type in `postfix operator %` and press return to declare an operator

4.  Type in 

``` java
postfix func %(value: Int) -> Int {
    value * 100
} 
```

and press return to define an implementation for this newly defined operator.

 

Expected results:

This should work

 

Actual results:

The following compiler error occurs:

``` java
error: repl.swift:11:14: error: operator implementation without matching operator declaration
postfix func %(value: Int) -> Int { 
```

 

Notes:

Any prefix, infix or postfix operator that is manually defined, is affected by this issue.

This issue is also reproducible in Swift Playgrounds if the operator declaration is executed separately from the implementation or call.

**Comment by belkadan** [comment]
Hm, operators don't go through normal name lookup, so maybe they need special handling?

@swift-ci create

**Comment by xedin** [comment]
Unfortunately REPL is no longer supported by swift executable.
