### ISSUE TITLE
[SR-11185] can't call extension method with default value in lldb

### ISSUE THREAD

**Issue by mattneub** [swiftlang/llvm-project#4334]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11185      |
   |Radar             | None         |
   |Original Reporter | @mattneub      |
   |Type              | Improvement    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Improvement        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ec5dbe92bd20fd98b29968e11d5ca6e7

  </details>

**Issue Description:**

Paste this into an iOS project:

``` java
@objc extension UIView {
    func test(ok:Bool = false) {
        print("test")
    }
}
```

Now pause at a breakpoint in \`viewDidLoad\` and talk to lldb in the console. You can say \`e self.view.test(ok:true)\`, but if you say \`e self.view.test()\` you get an error: "Couldn't lookup symbols: default argument 0". That seems like a bug.

**Comment by belkadan** [comment]
@dcci, I think there's a Radar for this too?

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
@compnerd had a WIP patch to fix this.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
And yes, I think there's a rdar (or at least a SR to duplicate this to). Let me find it.

**Comment by mattneub** [comment]
Thanks, I did look for a duplicate but feel free to close if I just missed it.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Duplicate of <https://bugs.swift.org/browse/SR-10994>
