### ISSUE TITLE
[SR-11075] [propertyWrapper] LLDB RPC server has crashed when running a very simple propertyWrapper code in playground

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4337]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11075      |
   |Radar             | None         |
   |Original Reporter | Philip (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963369-a8064576-014d-4c59-a2d8-b56cfb426acb.gz)

      
<details>
  <summary>Environment</summary>

Xcode 11 beta 3

macOS 14.5

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @dcci      |
   |Priority          | Medium      |

   

   md5: 9deb723ea582f3df84afa6c1c045aefa

  </details>

**Issue Description:**

**Code:** 

@propertyWrapper<a href="lldb-rpc-server_2019-07-06-064304_MBP-2018.crash" class="attachment">lldb-rpc-server_2019-07-06-064304_MBP-2018.crash</a>

struct Test {

    var wrappedValue: String

} 

@Test

var string = "test"

print(string)

 

**Issue:**

Xcode shows warning of "The LLDB RPC server has crashed. The crash log is located in ...

 

**And:**

-   The crash log attached

-   I tested this simple code as I found it seems any propertyWrapper sample code will cause the crash

**Comment by belkadan** [comment]
cc jingham@apple.com (JIRA User), @dcci

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Doug fixed this by disabling propertyWrappers in top level code.  
The current REPL doesn't crash.

``` java
  1> @propertyWrapper struct Test 
  2. {     var wrappedValue: String } 
  3.   
  4. @Test 
  5. var string = "test" 
  6. print(string) 
error: repl.swift:4:1: error: property wrappers are not yet supported in top-level code
@Test
^
```
