### ISSUE TITLE
[SR-9996] lldb crash in swift::Lowering::TypeConverter::getTypeLoweringForUncachedLoweredType

### ISSUE THREAD

**Issue by bobergj** [swiftlang/llvm-project#4341]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9996      |
   |Radar             | None         |
   |Original Reporter | @bobergj      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Cannot Reproduce    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963150-1739d44b-eb54-4e1a-893b-976af30b4ff1.gz)

      
<details>
  <summary>Environment</summary>

Swift 5

Xcode Version 10.2 beta 3 (10P99q)

macOS 10.14.3 (18D109)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ca2283280224db5723ce79757179513c

  </details>

**Issue Description:**

lldb rpc server crash when printing the argument of a nested function:

``` java
po ...
13  libsystem_pthread.dylib             0x00000001011f6e41 start_wqthread + 13
Message from debugger: The LLDB RPC server has crashed. The crash log is located in ~/Library/Logs/DiagnosticReports and has a prefix 'lldb-rpc-server'. Please file a bug and attach the most recent crash log.
```

lldb-rpc-server crash log attached,  relevant part of log:

``` java
Thread 9 Crashed:: RPC packet thread for client tid 0021770f (2193167)
0   libsystem_kernel.dylib              0x00007fff6e0c923e __pthread_kill + 10
1   libsystem_pthread.dylib             0x00007fff6e17fc1c pthread_kill + 285
2   libsystem_c.dylib                   0x00007fff6e0321c9 abort + 127
3   libsystem_malloc.dylib              0x00007fff6e1416e2 malloc_vreport + 545
4   libsystem_malloc.dylib              0x00007fff6e1414a3 malloc_report + 152
5   com.apple.LLDB.framework            0x000000010ec47f83 llvm::DenseMap<swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*, llvm::DenseMapInfo<swift::Lowering::TypeConverter::CachingTypeKey>, llvm::detail::DenseMapPair<swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*> >::grow(unsigned int) + 627
6   com.apple.LLDB.framework            0x000000010ec47cf7 llvm::detail::DenseMapPair<swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*>* llvm::DenseMapBase<llvm::DenseMap<swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*, llvm::DenseMapInfo<swift::Lowering::TypeConverter::CachingTypeKey>, llvm::detail::DenseMapPair<swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*> >, swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*, llvm::DenseMapInfo<swift::Lowering::TypeConverter::CachingTypeKey>, llvm::detail::DenseMapPair<swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*> >::InsertIntoBucketImpl<swift::Lowering::TypeConverter::CachingTypeKey>(swift::Lowering::TypeConverter::CachingTypeKey const&, swift::Lowering::TypeConverter::CachingTypeKey const&, llvm::detail::DenseMapPair<swift::Lowering::TypeConverter::CachingTypeKey, swift::Lowering::TypeLowering const*>*) + 103
7   com.apple.LLDB.framework            0x000000010ec449a5 swift::Lowering::TypeConverter::getTypeLoweringForUncachedLoweredType(swift::Lowering::TypeConverter::TypeKey) + 229
8   com.apple.LLDB.framework            0x000000010ec440ec swift::Lowering::TypeConverter::getTypeLowering(swift::Lowering::AbstractionPattern, swift::Type) + 492
9   com.apple.LLDB.framework            0x000000010ea7da7a swift::irgen::IRGenModule::getLoweredType(swift::Type) + 154
10  com.apple.LLDB.framework            0x000000010f5f1702 lldb_private::SwiftASTContext::GetSwiftTypeInfo(void*) + 98 
```

**Comment by belkadan** [comment]
Do you have a reproducing test case you can share?

cc @dcci

**Comment by bobergj** [comment]
Not at the moment as this happens in the middle of a pretty sizeable proprietary code base. But if you need some info about the function or variable in question (for example printing out some type information or running some lldb command), I can assist.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
This is going to be hard for us to diagnose without a reproducer, so if you can make the effort to have a synthetic testcase, it would be greatly appreciated.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
We fixed several instances of this so we encourage you to try with a new snapshot. FWIW, this bug is not actionable as is so I'm going to close it. Please reopen it if you have additional informations.
