### ISSUE TITLE
[SR-9697] REPL displays wrong boolean dictionary values

### ISSUE THREAD

**Issue by martinr448** [swiftlang/llvm-project#4346]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9697      |
   |Radar             | None         |
   |Original Reporter | @martinr448      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b89d33183decc6bd01384d5aad3702c8

  </details>

**Issue Description:**

(From <https://forums.swift.org/t/repl-prints-wrong-dictionary-values/19588.)> A dictionary with boolean values is displayed wrongly in the REPL, here the value is displayed as \`false\` instead of \`true\`:

``` java
Welcome to Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1). Type :help for assistance.
  1> let dict = ["foo" : true]
dict: [String : Bool] = 1 key/value pair {
  [0] = {
    key = "foo"
    value = false
  }
}
  2> dict
$R0: [String : Bool] = 1 key/value pair {
  [0] = {
    key = "foo"
    value = false
  }
}
```

\`print()\` shows the correct value, also accessing the value via subscript:

``` java
  3> print(dict)
["foo": true]
  4> dict["foo"]!
$R1: Bool = true
```

Tested with Swift 4.2.1 (Xcode 10.1) on macOS, and swift-4.2.1-RELEASE-ubuntu18.04 on Linux.

**Comment by benrimmington** [comment]
This appears to be fixed in a recent Swift 5.0 snapshot.

Although I don't know how or when it was fixed.

e.g. `Bool_SummaryProvider` in [SwiftFormatters.cpp](https://github.com/apple/swift-lldb/blob/master/source/Plugins/Language/Swift/SwiftFormatters.cpp) hasn't changed.

**Comment by belkadan** [comment]
I remember it being fixed but I can't find the bug for it. It was a problem with Dictionary, not Bool. jingham@apple.com (JIRA User)?

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Dictionary formatters changed quite a bit, and I also fixed a bug to take in account the padding (which might have fixed this).  
Please try with top of tree. Thanks!

**Comment by martinr448** [comment]
Works correctly with development snapshot from January 16, 2019.
