### ISSUE TITLE
[SR-9115] Add support for Python 3 to the LLDB SB module

### ISSUE THREAD

**Issue by pvieito** [swiftlang/llvm-project#4356]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9115      |
   |Radar             | None         |
   |Original Reporter | @pvieito      |
   |Type              | New Feature    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | New Feature        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: c6e7c6496dc4d4c85722692d418e7ec1

  </details>

**Issue Description:**

Add support for Python 3 to the LLDB SB module

**Comment by keith** [comment]
Can be closed, it's done
