### ISSUE TITLE
[SR-8374] Swift 4.2 lldb po failures

### ISSUE THREAD

**Issue by keith** [swiftlang/llvm-project#4364]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8374      |
   |Radar             | rdar://problem/42626690         |
   |Original Reporter | @keith      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Cannot Reproduce    |
        
<details>
  <summary>Environment</summary>

Xcode 10 beta 4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @dcci      |
   |Priority          | Medium      |

   

   md5: 1666c5c21076e977fc2aa5be2cb95d0f

  </details>

**Issue Description:**

If you compile this code with Xcode 10b4 with:

``` none
swiftc -g foo.swift -sdk `xcrun --show-sdk-path -sdk macosx`
```

``` none
import CoreFoundation
import Foundation

let a: CFString = "hi" as NSString
let b = a as String

print("hi")
```

In lldb if you run:

``` none
lldb -- ./foo
(lldb) br set -f foo.swift -l 7
(lldb) r
(lldb) fr v
(lldb) po a
```

You get these errors:

``` none
(lldb) po a
error: in auto-import:
failed to get module 'foo' from AST context
(lldb) po b
error: in auto-import:
failed to get module 'foo' from AST context
(lldb) fr v # no output
```

**Comment by belkadan** [comment]
@swift-ci create

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Looking at this.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Cannot reproduce on ToT on Mojave.

``` java
(lldb) po a
hi

(lldb) frame var a
(NSTaggedPointerString) a = 0x8c712a44ee9f9df3 "hi"
(lldb) frame var b
(String) b = "hi"
(lldb) p a
(NSTaggedPointerString) $R2 = 0x8c712a44ee9f9df3 "hi"
(lldb) p b
(String) $R4 = "hi"
(lldb) frame var b
(String) b = "hi"
```

Can you try updating your source? I think this might be a mismatch between lldb and swift, but I'm not sure.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Just to make sure, this is where I'm at:

``` java
locals-Mac-Pro:bin davide$ ./swiftc --version
Swift version 4.2-dev (LLVM a4d539e482, Clang 773ac0251a, Swift 31f2c75bb7)
locals-Mac-Pro:bin davide$ lldb 
locals-Mac-Pro:bin davide$ ../../lldb-macosx-x86_64/bin/lldb --version
lldb version 6.0.0 (https://github.com/apple/swift-lldb.git revision 873a338b5d8b74ed504c5e02e52d6972fe9bc513)
  Swift-4.2 (revision 31f2c75bb7928042bce90195b6473dbfe0188387)
  clang revision 773ac0251a7ea94c0b58d96353d4210a7eb2aeef
  llvm revision a4d539e482ca76290f3db6b775203ae230b34d42
```

(swift -\> master branch / lldb -\> stable branch)

**Comment by keith** [comment]
Sorry I must have built / tested with different versions, I didn't think that was the case, but I can't reproduce anymore with Xcode 10b4's Swift and lldb

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Also tried within Xcode beta 4 and I get the same.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
yay. Thanks.

**Comment by keith** [comment]
Sorry about that!
