### ISSUE TITLE
[SR-8285] REPL doesn't like nil with optional unowned/unowned(unsafe)

### ISSUE THREAD

**Issue by davezarzycki** [swiftlang/llvm-project#4365]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8285      |
   |Radar             | rdar://problem/42301922         |
   |Original Reporter | @davezarzycki      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Invalid    |
        
<details>
  <summary>Environment</summary>

Red Hat Fedora 28 with top-of-tree clang+llvm+lld as the local compiler.

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @davezarzycki      |
   |Priority          | Medium      |

   

   md5: a18d2d7cf822aa1dc372fa4ad4f2ac14

  </details>

**Issue Description:**

Top-of-tree Swift now enables optional types to be used with unowned/unowned(unsafe), but this confuses LLDB:

$ ./bin/swift  
Welcome to Swift version 4.2-dev. Type :help for assistance.  
1\> class C { unowned var next : C? }  
error: Couldn't lookup symbols:  
swift_allocObject  
swift_beginAccess  
swift_endAccess  
swift_registerTypeMetadataRecords  
swift_registerFieldDescriptors  
value witness table for Builtin.NativeObject  
type metadata accessor for Swift.Optional  
swift_deallocClassInstance  
swift_unownedRetainStrong  
swift_unownedRelease  
swift_release  
swift_unownedRetain

1\> let c = C()  
Process 31578 stopped

-   thread \#1, name = 'repl_swift', stop reason = signal SIGSEGV: invalid address (fault address: 0xbad0bad0)  
    frame \#0: 0x00000000bad0bad0  
    error: memory read failed for 0xbad0ba00  
    Target 0: (repl_swift) stopped.  
    c: C = \<extracting data from value failed\>

Execution interrupted. Enter code to recover and continue.  
Enter LLDB commands to investigate (type :help for assistance.)  
2\>

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Yes, this is clearly a bug. @davezarzycki are you going to work on this or you want us to take a look?  
@swift-ci create

**Comment by davezarzycki** [comment]
For clarity: it seems like there are two bugs here. First, the "Couldn't lookup symbols" noise. And second, the SIGSEGV bug while creating an object with an optional unowned. I'd prefer that this bug be about the latter. Thanks!

As to task assignment, the REPL isn't on my critical path and therefore I don't foresee working on this in the short to medium term. Sorry. :-(

**Comment by davezarzycki** [comment]
Interesting. I rarely test the Linux REPL, but anecdotally speaking, I think it has been broken for a long time. Then again, I never install the built product, and I build/test Swift with the ToT llvm+clang compiler, so maybe I've wandered deep in the weeds. I don't know if this information helps.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
I'm afraid I really can't reproduce this on my Linux machine, David.

``` java
davide@rad:~/work/build/Ninja-ReleaseAssert/lldb-linux-x86_64/bin$ ./lldb --repl
Welcome to Swift version 4.2-dev (LLVM 748f9878c8, Clang 6c624d9bad, Swift 86c26a9e32). Type :help for assistance.
  1> class C { unowned var next : C? }
  2>  let c = C()
c: C = {
  next = nil
}
```

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
FWIW, this is my configuration:

uname:

``` java
 uname -a
Linux 4.4.0-45-generic #&#8203;66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

``` java
$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

To the best of my understanding, you're building with Red hat, which isn't quite a supported (officially) system. Might I ask you to try with Ubuntu?

**Comment by davezarzycki** [comment]
I don't have access to an Ubuntu machine. At this point, I'd wager that the issue is not the OS but that I prefer unified builds over the slow "build-script". Let's just close this. Does that work for you?

**Comment by davezarzycki** [comment]
Confirmed. The LLDB test suite fails spectacularly with unified builds, but when I try a \`build-script\` build, only two LLDB tests fail (pull request pending). Let's close this.
