### ISSUE TITLE
[SR-7728] `:type lookup Swift` aborts the REPL

### ISSUE THREAD

**Issue by 05262b81-54a9-4fe1-bf6a-96f8042de10e** [swiftlang/llvm-project#4369]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7728      |
   |Radar             | rdar://40417941         |
   |Original Reporter | @lilyball      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)  
Target: x86_64-apple-darwin17.5.0

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, LLDB for Swift    |
   |Labels            | Bug, CompilerCrash        |
   |Assignee          | @dcci      |
   |Priority          | Medium      |

   

   md5: 617afca88c50202d981754eecc688368

  </details>

**Issue Description:**

In the REPL, running `:type lookup Swift` prints a good chunk of the Swift module, then unceremoniously aborts the REPL and leaves me back at the shell, without even printing a error (error code 139). My best guess is there's some declaration in the Swift module that doesn't serialize back to ~~Obj-C~~ Swift properly.

Steps to reproduce:

1\. Run `swift`  
2. At the REPL run `:type lookup Swift`

**Comment by belkadan** [comment]
I'm not sure what ObjC has to do with anything, but yes, this should work.

@swift-ci create

**Comment by 05262b81-54a9-4fe1-bf6a-96f8042de10e** [comment]
I'm not sure why I said Obj-C (I blame sleep deprivation). I meant some declaration that doesn't serialize back into Swift properly.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
<https://github.com/apple/swift-lldb/pull/647>

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Fixed, thanks for your report, Kevin.
