### ISSUE TITLE
[SR-7686] Swift REPL hangs (only after using SIMD functions?)

### ISSUE THREAD

**Issue by jepers** [swiftlang/llvm-project#4370]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7686      |
   |Radar             | rdar://problem/40227912         |
   |Original Reporter | @jepers      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f92838a25504e33f4781302d20820262

  </details>

**Issue Description:**

Related discussion: <https://forums.swift.org/t/swift-repl-hangs/12644/1>

``` none
> swift
Welcome to Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.39.1). Type :help for assistance.

1> import simd

2> 1 * 2 / 3.0
$R0: Double = 0.66666666666666663

3> simd_normalize(float2(1, 2))
$R1: simd_float2 = {
  _vector = {}
}

4> 1 * 2 / 3.0
```

The REPL hangs after pressing return for this expression (note that the same expression worked the first time, before the simd function was called).

**Comment by belkadan** [comment]
@swift-ci create

**Comment by jepers** [comment]
Seems like this issue has been fixed in Xcode 10. Should I close it?

**Comment by belkadan** [comment]
Yep, sorry. Looks like this was fixed in <https://github.com/apple/swift-lldb/pull/635.>
