### ISSUE TITLE
[SR-7474] LLDB should run the AST verifier after doing any AST manipulations

### ISSUE THREAD

**Issue by belkadan** [swiftlang/llvm-project#4373]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7474      |
   |Radar             | rdar://problem/39544116         |
   |Original Reporter | @belkadan      |
   |Type              | Improvement    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Improvement        |
   |Assignee          | @dcci      |
   |Priority          | Medium      |

   

   md5: d3b4d71d74559c6d3ff1fae03d6073ec

  </details>

**Issue Description:**

In <https://github.com/apple/swift/pull/15996> I'm adding a check to the Swift AST verifier that `open` is not used on declarations where it doesn't make sense (like a `typealias`). However, LLDB's unilaterally splatting `open` and `public` on things defined in the REPL to make sure they can be accessed later. That's a fine thing to do, but the condition where it was doing so wasn't quite right. I'm fixing that, but I couldn't write a real test for it because the AST verifier runs as part of Swift type checking, and is not run again after LLDB does its manipulation.

LLDB should call `swift::verify(SourceFile &SF)` (which is a no-op in release builds) after it does any AST manipulation, to make sure that the resulting AST still matches what the later phases of the compiler will expect.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
@swift-ci create

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Fixed <https://github.com/apple/swift-lldb/pull/570>
