### ISSUE TITLE
[SR-7114] REPL hangs for no apparent reason

### ISSUE THREAD

**Issue by xwu** [swiftlang/llvm-project#4377]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7114      |
   |Radar             | rdar://problem/38142243         |
   |Original Reporter | @xwu      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

Apple Swift version 4.1 (swiftlang-902.0.34 clang-902.0.30)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: f41adada05af25ed38dd6e5c1b56d8d1

  </details>

**duplicates**:  
* [SR-7193](https://bugs.swift.org/browse/SR-7193) Segfaults after using KeyPath on array in REPL   

**Issue Description:**

Here are three lines of code (rather fun and educational ones, but besides the point):

    let a = 9007199254740991.0
    (a * a - a * a).squareRoot()
    (a * a).addingProduct(-a, a).squareRoot()

If I enter these line-by-line into a REPL, it'll just hang after line 3.

But it's not the *content* of line 3 that's the problem. I can enter line 1, line 3, *then* line 2, and it'll hang after I press enter the third time (line 2).

I've notice this lately experimenting with various other expressions; the REPL will just hang, and I'll start over in a new Terminal tab and the same expression will be fine. But it's annoying.

**Comment by belkadan** [comment]
@swift-ci create

**Comment by belkadan** [comment]
Whoops, turns out this was the same as SR-7193.
