### ISSUE TITLE
[SR-6156] LLDB: warning: initialization of variable '$__lldb_error_result'

### ISSUE THREAD

**Issue by keith** [swiftlang/llvm-project#4384]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6156      |
   |Radar             | rdar://problem/35002947         |
   |Original Reporter | @keith      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 41         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @slavapestov      |
   |Priority          | Medium      |

   

   md5: 48509e726972078e013416019229b090

  </details>

**Issue Description:**

This test case:

``` none
import Foundation

final class Foo {
    func bar() {
        DispatchQueue.main.async { [weak self] in
            if let `self` = self {
                print(self)
            }
        }
    }
}

let foo = Foo()
foo.bar()
dispatchMain()
```

Causes this error when attempting to \`po self\` inside of the dispatch closure:

``` none
error: warning: <EXPR>:12:9: warning: initialization of variable '$__lldb_error_result' was never used; consider replacing with assignment to '_' or removing it
    var $__lldb_error_result = __lldb_tmp_error
    ~~~~^~~~~~~~~~~~~~~~~~~~
    _

error: <EXPR>:18:5: error: value of type 'Foo' has no member '$__lldb_wrapped_expr_0'
    $__lldb_injected_self.$__lldb_wrapped_expr_0(
    ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
```

To reproduce this you can compile and debug it with this:

``` none
$ swiftc -g foo.swift
$ lldb ./foo
(lldb) target create "./foo"
Current executable set to './foo' (x86_64).
(lldb) br set -f foo.swift -l 7
Breakpoint 1: where = foo`closure #&#8203;1 () -> () in foo.Foo.bar() -> () + 118 at foo.swift:7, address = 0x0000000100001ec6
(lldb) r
...
Target 0: (foo) stopped.
(lldb) po self
error: warning: <EXPR>:12:9: warning: initialization of variable '$__lldb_error_result' was never used; consider replacing with assignment to '_' or removing it
    var $__lldb_error_result = __lldb_tmp_error
    ~~~~^~~~~~~~~~~~~~~~~~~~
    _

error: <EXPR>:18:5: error: value of type 'Foo' has no member '$__lldb_wrapped_expr_0'
    $__lldb_injected_self.$__lldb_wrapped_expr_0(
    ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~
```

This is probably the same core issue as <https://bugs.swift.org/browse/SR-3886> but I wanted to file it separately since it has a different test case.

**Comment by slavapestov** [comment]
@swift-ci create

**Comment by NachoSoto** [comment]
FWIW I think I've been seeing this since Swift 1.0.

**Comment by slavapestov** [comment]
So it's not a regression? Sorry, management won't let us fix it 😉

**Comment by keith** [comment]
I've made some progress on this. So the problem for *this specific case* is that when lldb attempts to find \`self\` [here](https://github.com/apple/swift-lldb/blob/3c3bd53f6862ec52ab89134b89532bc731a89d45/source/Plugins/ExpressionParser/Swift/SwiftUserExpression.cpp#L159), it finds the optional one, and ends up adding the [extension to Optional](https://github.com/apple/swift-lldb/blob/3c3bd53f6862ec52ab89134b89532bc731a89d45/source/Plugins/ExpressionParser/Swift/SwiftUserExpression.cpp#L242-L245), yet the \`self\` that ends up getting accessed is the non optional one, so the extension doesn't apply. This is the cause of the second half of this error.

This isn't super surprising since in this case you can even see the problem by running \`fr v\`:

``` none
(@lvalue second.Foo?) self = 0x0000000101303740
(second.Foo) self = 0x0000000101303740 {}
```

Since you end up with multiple self vars here. I'm not exactly sure what the solution is yet, or if it's even on the lldb side, but I'm still looking into it.

**Comment by keith** [comment]
Upon more investigation, the problem isn't the multiple \`self\` variables, it's that where lldb is fetching the variables from, SymbolContext-\>GetFunctionBlock-\>GetBlockVariableList, only includes the optional self, and not the non-optional one. You can see this using the python API to access the same variables:

``` none
# From some lldb python function
frame = context.GetFrame()
block = frame.GetFunction().GetBlock()
# All the Trues means don't filter out any specific types of variables
variables = block.GetVariables(frame, True, True, True, lldb.eDynamicDontRunTarget)
for variable in variables:
    print variable
```

In this case you end up with just the optional \`self\`. If you instead access the variables directly from the frame, you get both.

**Comment by keith** [comment]
Since <https://github.com/apple/swift/pull/15306> you can now do this without the backticks, but lldb still has this issue (unsurprisingly)

**Comment by omochi** [comment]
I recorded video about same issue.  
<https://twitter.com/omochimetaru/status/1047384921180758016>

**Comment by slavapestov** [comment]
I'm looking at this now, but at least some of you will be disappointed... 🙂 I suspect there are multiple root cause failures that all manifest as an error "value of type 'Foo' has no member '$\_\_lldb_wrapped_expr_0'", one of them being this issue with a shadowed 'self' declaration. However, once I fix this issue, we can see what else remains.

**Comment by keith** [comment]
The original specific example here has been fixed for a while. If anyone else has a new repro case please file a new ticket!
