### ISSUE TITLE
[SR-5572] Interactive CLI REPL not working?

### ISSUE THREAD

**Issue by davezarzycki** [swiftlang/llvm-project#4387]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5572      |
   |Radar             | rdar://problem/29039602         |
   |Original Reporter | @davezarzycki      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: a7fa14d4f516979ecbe2926a334f7382

  </details>

**Issue Description:**

This seems like a bug. Why does the interactive command line REPL put each input line into separate modules?

Welcome to Apple Swift version 4.0 (swiftlang-900.0.54.10 clang-900.0.31). Type :help for assistance.  
1\> open class A {}  
2\> class B : A {}  
error: repl.swift:2:7: error: cannot inherit from non-open class 'A' outside of its defining module  
class B : A {}  
^

2\>

**Comment by belkadan** [comment]
@slavapestov just fixed this! Got the bug number?

**Comment by slavapestov** [comment]
Here is the fix: <https://github.com/apple/swift-lldb/pull/244>
