### ISSUE TITLE
[SR-4580] Tuple-swapping in REPL can segfault

### ISSUE THREAD

**Issue by natecook1000** [swiftlang/llvm-project#4389]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4580      |
   |Radar             | rdar://problem/31610342         |
   |Original Reporter | @natecook1000      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @natecook1000      |
   |Priority          | Medium      |

   

   md5: 4553d26f07e5447fcbb868620432a6b2

  </details>

**Issue Description:**

If I enter the following code in the Swift REPL, line by line, I get a segfault:

``` java
var a = Array(1...5)
(a[1], a[3]) = (a[3], a[1])

import AppKit

var p = CGPoint(x: 1, y: 2)
(p.x, p.y) = (p.y, p.x)
```

If I don't use the first two lines, the remainder executes without issue. If I paste in the whole batch or compile them in a file, there's also no problem.

**Comment by natecook1000** [comment]
@swift-ci Create

**Comment by jckarter** [comment]
@swift-ci create

**Comment by jckarter** [comment]
Can lldb pre-load the Foundation overlay in that case to avoid that kind of issue?

**Comment by jckarter** [comment]
The other approach would be to fix the standard library to pick up when Foundation is dynamically loaded and adjust itself accordingly. It isn't totally out of the realm of possibility that someone would dlopen Foundation at runtime even outside the REPL. Jim, did you happen to see where exactly in the library we were making different initialization choices?

**Comment by jckarter** [comment]
Nate, can you confirm this works for you now?
