### ISSUE TITLE
[SR-4433] lldb expression command can't handle structs with no elements

### ISSUE THREAD

**Issue by aciidgh** [swiftlang/llvm-project#4391]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4433      |
   |Radar             | None         |
   |Original Reporter | @aciidb0mb3r      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | jingham@apple.com (JIRA)      |
   |Priority          | Medium      |

   

   md5: 20d04d201ee93e9c742ae61392fe22c7

  </details>

**duplicates**:  
* [SR-4204](https://bugs.swift.org/browse/SR-4204) LLDB fails printing variables when `self` refers to an empty struct  

**Issue Description:**

Unfortunately I am unable to use lldb even on a simple program 🙁

``` java
struct Bar {
    func bar(foos: [String]) {
        print(foos)
    }
}

Bar().bar(foos: [
    "xxx",
])
```

    $ xcrun --find swift
    /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2017-03-26-a.xctoolchain/usr/bin/swift
    $ swiftc -g main.swift && lldb main -o "b main.swift:3" -o r -o "po foos" -b
    (lldb) target create "main"
    Current executable set to 'main' (x86_64).
    (lldb) b main.swift:3
    Breakpoint 1: where = main`main.Bar.bar (foos : Swift.Array<Swift.String>) -> () + 12 at main.swift:3, address = 0x00000001000011bc
    (lldb) r
    Process 58344 stopped
    * thread #&#8203;1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
        frame #&#8203;0: 0x00000001000011bc main`Bar.bar(foos=1 value, self=main.Bar @ scalar) -> () at main.swift:3
       1    struct Bar {
       2        func bar(foos: [String]) {
    -> 3            print(foos)
       4        }
       5    }
       6
       7    Bar().bar(foos: [

    Process 58344 launched: '/private/tmp/Sample/Sources/exe/main' (x86_64)
    (lldb) po foos
    error: Couldn't materialize: couldn't get the value of self: extracting data from value failed
    error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression

**Comment by belkadan** [comment]
Reproduced. `frame variable` works, but `po` does not. jingham@apple.com (JIRA User)?

**Comment by aciidgh** [comment]
Hm, I was trying to reduce a big test case for the same error. Is it fine if I file debugger reports with entire project attached?
