### ISSUE TITLE
[SR-4326] lldb prints strange numbers when interpreting optional unsigned values

### ISSUE THREAD

**Issue by phausler** [swiftlang/llvm-project#4393]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-4326      |
   |Radar             | None         |
   |Original Reporter | @phausler      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | jingham@apple.com (JIRA)      |
   |Priority          | Medium      |

   

   md5: 4bf1f93b21119718ade2f1efa9d50ac5

  </details>

**duplicates**:  
* [SR-4091](https://bugs.swift.org/browse/SR-4091) Incorrect result shown in REPL for 'UInt8?'  

**Issue Description:**

given the code \`let v: UInt8? = 128\`  
issuing \`p v\` results in the following

    (lldb) p v
    (UInt8?) $R0 = -128

issuing \`p v!\` results in the following

    (lldb) p v!
    (UInt8) $R1 = 128

it seems that the top bit of the optional is being reinterpreted as memory of a Int16 instead?

**Comment by belkadan** [comment]
I thought this was fixed with SR-1007, but apparently not. cc jingham@apple.com (JIRA User)

**Comment by phausler** [comment]
It is worth noting this only applies to optional values and I have reasonably proven to myself that it is a lldb issue and not actually a swift issue (which would be quite scary if it was).
