### ISSUE TITLE
[SR-1766] [master-next] TestObjCStructArgument.py test_with_python_api() gmodules variant fails after merge

### ISSUE THREAD

**Issue by a0332500-857b-4d6a-874e-50b63b66b387** [swiftlang/llvm-project#4397]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1766      |
   |Radar             | None         |
   |Original Reporter | @trfiala      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

macOS 10.11.5, in-tree clang, master-next branch configuration

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: cb3e166b8bc439619e5453a6fc01fd4e

  </details>

**Issue Description:**

After the latest merge of upstream LLDB, TestObjCStructArgument.py's single test method fails in the gmodules debug info variant on macOS 10.11.5.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Marked xfail here:

commit ef7a77e91f8c1fd826c76bfef6c2c638f0d7851d (HEAD -\> master-next, origin/master-next, upstream-merge-r272635)  
Author: Todd Fiala \<todd.fiala@gmail.com\>  
Date: Tue Jun 14 18:23:25 2016

xfail TestObjCStructArgument.py, gmodule variant on macOS

Tracked by:  
<https://bugs.swift.org/browse/SR-1766>

**Comment by adrian-prantl** [comment]
This is no longer applicable.
