### ISSUE TITLE
[SR-1764] [master-next] TestObjCMethods2.test_NSError_po() gmodules variant fails after merge

### ISSUE THREAD

**Issue by a0332500-857b-4d6a-874e-50b63b66b387** [swiftlang/llvm-project#4399]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1764      |
   |Radar             | None         |
   |Original Reporter | @trfiala      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

macOS El Capitan, 10.11.5 (15F34)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: ce9b178cf558216d685abb7530554c17

  </details>

**Issue Description:**

The gmodules variant of test_NSError_po() within TestObjCMethods2.py is failing after I merged in LLVM.org LLDB svn trunk up through and including r272635. That merge will be committed shortly.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
This is using the in-tree clang with compiler-rt included. It's the typical master-next combo:  
LLVM: stable-next  
clang: stable-next  
compiler-rt: stable-next  
swift: master-next  
LLDB: master-next

Note that at the moment I'm doing this, clang and LLVM haven't been updated in a long while (in merge terms), nor has swift (although more recent than clang/LLVM).

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Marked xfail here:

commit a2d6bb612260bcceaa6e49b52096d193d4c8dd1e  
Author: Todd Fiala \<todd.fiala@gmail.com\>  
Date: Tue Jun 14 17:59:28 2016

xfail TestObjCMethods2.test_NSError_po_gmodules() on macOS

Tracked by:  
<https://bugs.swift.org/browse/SR-1764>

**Comment by adrian-prantl** [comment]
This is no longer applicable.
