### ISSUE TITLE
[SR-1301] PR Linux bot always fails LLDB lots of REPL tests

### ISSUE THREAD

**Issue by bitjammer** [swiftlang/llvm-project#4407]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1301      |
   |Radar             | None         |
   |Original Reporter | @bitjammer      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Duplicate    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @bitjammer      |
   |Priority          | Medium      |

   Watchers: @shahmishal

   md5: 259fc5bc197bcc6981138496fb544f3f

  </details>

**duplicates**:  
* [SR-1300](https://bugs.swift.org/browse/SR-1300) LLDB REPL tests fail on Ubuntu when not run from install layout  

**Issue Description:**

<https://ci.swift.org/job/swift-PR-Linux/>

Build 1209 was the last successful build on the PR Linux bot.

These REPL tests are failing:

\`\`\`  
ERROR: testREPL (repl/quicklookobject/TestREPLQuickLookObject.py)  
ERROR: testREPL (repl/recursive_class/TestREPLRecursiveClass.py)  
ERROR: testREPL (repl/basic/TestREPLBasic.py)  
ERROR: testREPL (repl/classes/TestREPLClasses.py)  
ERROR: testREPL (repl/dyntype/TestREPLDynamicType.py)  
ERROR: testREPL (repl/array/TestREPLArray.py)  
ERROR: testREPL (repl/pounwrapping/TestPOUnwrapping.py)  
ERROR: testREPL (repl/lazy_reverse/TestLazyReverse.py)  
ERROR: testREPL (repl/type_lookup/TestREPLTypeLookup.py)  
ERROR: testREPL (repl/func_definition/TestREPLFunctionDefinition.py)  
ERROR: testREPL (repl/multilevelarrays/TestMultilevelArrays.py)  
ERROR: testREPL (repl/subclassing/TestREPLSubclassing.py)  
ERROR: testREPL (repl/closures/TestREPLClosure.py)  
ERROR: testREPL (repl/structs/TestREPLStructs.py)  
ERROR: testREPL (repl/po_repl_type/TestREPLPOReplType.py)  
\`\`\`

**Comment by bitjammer** [comment]
@shahmishal Does the bot do clean builds? Do you think it needs a clean?

**Comment by shahmishal** [comment]
This is related to <https://bugs.swift.org/browse/SR-1300>

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
I've got a fix for this in master-next, and will be bringing this into the master branch later today.

Also, closing since it is a duplicate.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Closing due to dupe (SR-1300).
