### ISSUE TITLE
[SR-18] OS X: provide error when 'swift/utils/build-script -l' uses unsupported configuration

### ISSUE THREAD

**Issue by a0332500-857b-4d6a-874e-50b63b66b387** [swiftlang/llvm-project#4416]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-18      |
   |Radar             | None         |
   |Original Reporter | @trfiala      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Won't Do    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @trfiala      |
   |Priority          | Medium      |

   

   md5: 41628e4ad536ee3accb299596e07f8e8

  </details>

**Issue Description:**

Running the following:

swift/utils/build-script -r -l

will fail in a cryptic way during the lldb build phase. The underlying issue is that the default Xcode build configuration gets used when an unsupported configuration is specified, but the default configuration is not something that will ever build properly on a developer machine.

This was not caught since the lldb/scripts/build-swift-cmake.py script, which wraps build-script, only allows the valid Debug and Release options to be passed to build-script.

Workaround:  
Limit builds to Debug or Release with no asserts when using '-l' to add Swift LLDB into the mix.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
An alternative workaround is to use lldb/scripts/build-swift-cmake.py (use --help to see the options). But this only makes sense for Swift LLDB-focused developers. It is just a light wrapper around the Swift build-script, adding repository cloning/updating and other LLDB-centric options like including the system debugserver or including no debugserver on OS X builds.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
<https://github.com/apple/swift/commit/b08610bc3e4acfc2842349e4e661a38b93d4dd27>

**Comment by gribozavr** [comment]
Todd reverted this: <https://github.com/apple/swift/commit/02a493b8380bbcb5c4bf2e123db0b6d79c95dc8f>

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
I'm going to reimplement this, checking in build-script-impl so it catches any options passed to build-script that are intended for direct consumption by build-script-impl. In the case of build presets, we hit an issue where direct control of the lldb build variant was missed because it was not using the build-script mechanism to control build variant; rather, it was specifying the build-script-impl variant directly.

Something about that is a little icky; nonetheless, checking in build-script-impl is the most basic (and thorough) way to handle this.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
SR-19 addresses the common RelWithDebInfoAsserts build variant that this issue here was meant to resolve.

I'll just make sure LLDB can build with the configurations that build-script can generate.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Not to be fixed. Rather, I'll be adding configurations we need.
