### ISSUE TITLE
[SR-14] Wrong python version selected when building swift-lldb

### ISSUE THREAD

**Issue by b9e45994-f1ab-4caa-ab67-04c71c9dbfb6** [swiftlang/llvm-project#4417]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-14      |
   |Radar             | None         |
   |Original Reporter | @octoploid      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Cannot Reproduce    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961013-c31af7b0-e761-4b82-80d4-c469a376d235.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 3         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: d379de56b4707da9e6dfce4bc46064ff

  </details>

**Issue Description:**

On my system both python-3.4 and python-2.7 are installed.  
swift-lldb selects the wrong version (3.4):

    ...
    [6/840] Building CXX object scripts/Python/modules/readline/CMakeFiles/readline.dir/readline.cpp.o
    FAILED: /usr/local/bin/clang++   -DHAVE_PROCESS_VM_READV -DHAVE_ROUND -DLIBXML2_DEFINED -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Dreadline_EXPOR
    TS -Iscripts/Python/modules/readline -I/var/tmp/lldb/scripts/Python/modules/readline -I/var/tmp/lldb/include -Iinclude -I/var/tmp/build/Ninja-ReleaseAssert/llvm-linux-x86_64/
    include -I/var/tmp/build/Ninja-ReleaseAssert/llvm-linux-x86_64/tools/clang/include -I/var/tmp/llvm/include -I/var/tmp/llvm/tools/clang/include -I/var/tmp/build/Ninja-ReleaseA
    ssert/swift-linux-x86_64/include -I/var/tmp/swift/include -I/var/tmp/lldb/source -I/usr/include/python3.4 -I/var/tmp/lldb/tools/clang/include -I../clang/include -I/usr/includ
    e/libxml2 -Werror=date-time -std=c++11 -fcolor-diagnostics -ffunction-sections -fdata-sections -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-strict-aliasing -Wno-dep
    recated-register -Wno-vla-extension  -fno-exceptions -fno-rtti -Wno-macro-redefined -O3 -DNDEBUG -fPIC -MMD -MT scripts/Python/modules/readline/CMakeFiles/readline.dir/readli
    ne.cpp.o -MF scripts/Python/modules/readline/CMakeFiles/readline.dir/readline.cpp.o.d -o scripts/Python/modules/readline/CMakeFiles/readline.dir/readline.cpp.o -c /var/tmp/ll
    db/scripts/Python/modules/readline/readline.cpp
    /var/tmp/lldb/scripts/Python/modules/readline/readline.cpp:68:34: error: assigning to 'char *(*)(FILE *, FILE *, const char *)' (aka 'char *(*)(_IO_FILE *, _IO_FILE *, const 
    char *)') from incompatible type 'char *(FILE *, FILE *, char *)' (aka 'char *(_IO_FILE *, _IO_FILE *, char *)'): type mismatch at 3rd parameter ('const char *' vs 'char *')
        PyOS_ReadlineFunctionPointer = simple_readline;
                                     ^ ~~~~~~~~~~~~~~~
    /var/tmp/lldb/scripts/Python/modules/readline/readline.cpp:70:5: error: use of undeclared identifier 'Py_InitModule4'
        Py_InitModule4(
        ^
    2 errors generated.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Hi Markus,

Thanks for filing the bug!

Can you tell me a bit more about your setup?

Which OS exactly, which packages are installed, and how you installed them? I'd like to make sure I have a valid repro environment.

I think this could be a bad interaction with some work being done in llvm.org lldb to support Python 3.x for Windows. The code for Linux in that override readline Python module (the site of your error) looks to be no longer valid for Python 3.x. (It might be unrelated, but I've built on Linux quite a bit in the past with both python 2 and 3 installed and hadn't hit this back then. I think this has crept in somewhat recently).

I'd be inclined to try to prevent a Python 3.x from being chosen on Linux for now.

Thanks in advance for digging up and passing along the repro environment!

**Comment by b9e45994-f1ab-4caa-ab67-04c71c9dbfb6** [comment]
Trying to prevent Python 3.x from being chosen on Linux looks like the right fix.

I'm running Gentoo. The default Python version is 2.7.10. Python 3.4.3 is also installed.  
I don't think that the specifics of the distro matter much for this issue.

Just running ":%s/python3.4/python2.7/g" on /var/tmp/build/Ninja-ReleaseAssert/lldb-linux-x86_64/build.ninja in vim fixed the issue for me...

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
The bug linked upstream is the place where this issue should be fixed. After resolving there, it can be cherry picked into swift.org swift-lldb.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Okay, thanks Markus. I had thought this was on an Ubuntu system, but thanks for clarifying it was Gentoo. Haven't been there for a while, but that's a nice and clean system! (I used to do Gentoo on PowerPC Macs back in early 2000s in addition to the x86 machines).

I'm glad you have a work-around. Let's keep this open until we have it really resolved for others, though. The llvm.org bug will track the real work, but that's discoverable from here now.

**Comment by Dante-Broggi** [comment]
Is this resolved? If so, this should be closed.

**Comment by adrian-prantl** [comment]
Please reopen if this is still an issue.
