### ISSUE TITLE
[SR-13275] Clang module breadcrumbs remaining in binaries even with '-no-clang-module-breadcrumbs'

### ISSUE THREAD

**Issue by thii** [swiftlang/llvm-project#4422]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13275      |
   |Radar             | rdar://problem/66058061         |
   |Original Reporter | @thii      |
   |Type              | Bug    |

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963901-7708b001-f754-4f0b-b014-3b8d3b04c282.gz)

      
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: a04ada4e3d0a10ab980e02c3c4c34a51

  </details>

**Issue Description:**

Consider the following code:

``` java
import Foundation

extension NSString {
    func test() {
        let _ = NSMakeRange(1, 2)
    }
}
```

When compiling with the following flag:

``` java
-Xfrontend -no-clang-module-breadcrumbs
```

it still produces a binary that has the Clang module breadcrumbs being embedded.

**Comment by adrian-prantl** [comment]
@swift-ci create

**Comment by keith** [comment]
richardh (JIRA User) related to the comment on the PR about limiting debug-ability, did you notice any specific downsides in that fix?

**Comment by keith** [comment]
@adrian-prantl are there some specifics to look out for here?

**Comment by keith** [comment]
I think everything is resolved here, except knowing specifics of the downsides of this flag. @adrian-prantl Are there other issues you know about?

**Comment by adrian-prantl** [comment]
Sounds good, thanks!
