### ISSUE TITLE
[SR-13103] lldb cannot evaluate optional date objects

### ISSUE THREAD

**Issue by LucianoPAlmeida** [swiftlang/llvm-project#4424]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-13103      |
   |Radar             | rdar://problem/64947443         |
   |Original Reporter | @LucianoPAlmeida      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Duplicate    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963869-d58bd114-405a-4dcc-8cb3-b3c1cc0f1bfb.gz)

      
<details>
  <summary>Environment</summary>

Xcode 11.5

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 860dffc3d45bba6f640fe0e0a09ec751

  </details>

**is duplicated by**:  
* [SR-11593](https://bugs.swift.org/browse/SR-11593) REPL incorrectly reports URL as nil  

**Issue Description:**

Although we indeed have values on the date objects, lldb is failing to evaluate them and is always showing nil(left side).

The \`p\` command docs state that it \`Displays any returned value with LLDB's default formatting.\` Which maybe be that date objects do not have a default formating withing lldb?

But independently of that, this seems like a bug because we shouldn't see \`nil\` as the value. 

 

![](Screen Shot 2020-06-27 at 19.19.23.png)

**Comment by LucianoPAlmeida** [comment]
cc theindigamer (JIRA User) 🙂

**Comment by typesanitizer** [comment]
@swift-ci create

**Comment by poya** [comment]
Looks like duplicate of SR-11593

**Comment by LucianoPAlmeida** [comment]
Seems like it indeed a dupe, theindigamer (JIRA User) should we close this as dupe?

**Comment by typesanitizer** [comment]
Done!
