### ISSUE TITLE
[SR-12794] Repl emitting warning: "adding which has a base that is less than the function's low PC"

### ISSUE THREAD

**Issue by augusto2112** [swiftlang/llvm-project#4427]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12794      |
   |Radar             | None         |
   |Original Reporter | @augusto2112      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b2329291ac6e740507bd61476c3c44b0

  </details>

**duplicates**:  
* [SR-8690](https://bugs.swift.org/browse/SR-8690) swift REPL error: adding range [0x1464a-0x146ba) which has a base that is less than the function's low PC  

**Issue Description:**

Starting the repl emits the warning:

``` java
error: ld-2.27.so 0x7fffffff0005c564: adding range [0x1464a-0x146ba) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0x7fffffff0005c564: adding range [0x146d0-0x146d6) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0x7fffffff0005c5c5: adding range [0x1464a-0x146ba) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message
error: ld-2.27.so 0x7fffffff0005c5c5: adding range [0x146d0-0x146d6) which has a base that is less than the function's low PC 0x14dc0. Please file a bug and attach the file at the start of this error message 
```

Which is emitted in the function SymbolFileDWARF::ParseBlocksRecursive.

This warning is already present in the latest release of Swift for Ubuntu (April 29th).

@adrian-prantl @vedantk

**Comment by vedantk** [comment]
This might be a bug in whichever compiler built ld.so. Can you get lldb to dump out the pretty-printed DIE and tag for the function it’s complaining about, so we can be sure?
