### ISSUE TITLE
[SR-11897] LLDB can't load type information

### ISSUE THREAD

**Issue by glbrntt** [swiftlang/llvm-project#4432]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11897      |
   |Radar             | rdar://problem/57625175         |
   |Original Reporter | @glbrntt      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

-   Ubuntu 16.04

-   Swift 5.1.2

 

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: d1fa24acc590247a5501eada8eb85dbb

  </details>

**duplicates**:  
* [SR-7932](https://bugs.swift.org/browse/SR-7932) Cannot load Swift type information; AST validation error: The serialized module is corrupted. / Swift expressions require OS X 10.10 / iOS 8 SDKs or later  

**Issue Description:**

I was trying to debug a sigsegv in one of the SwiftNIO tests and ran it with lldb:

`$ while time lldb --batch -o run -k "image list" -k "register read" -k "bt all" -k "exit 134" .build/debug/swift-nioPackageTests.xctest – NIOTests.ChannelTests/testDescriptionCanBeCalledFromNonEventLoopThreads; do true; done`

When the test eventually failed this was the output of bt all:

   
`(lldb) bt all``/Users/georgebarnett/workspace/swift-nio/.build/debug/swift-nioPackageTests.xctest: Cannot load Swift type information; AST validation error: The serialized module is corrupted.``Unable to load module.`

**Comment by weissi** [comment]
@swift-ci create

**Comment by weissi** [comment]
CC @dcci

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
@vedantk is looking at this very one

**Comment by adrian-prantl** [comment]
I'm pretty sure this is a dupe of SR-7932.
