### ISSUE TITLE
[SR-12867] REPL: Autocomplete for debugger commands leaves out characters

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4466]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12867      |
   |Radar             | None         |
   |Original Reporter | palle (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @poya      |
   |Priority          | Medium      |

   

   md5: 1d4fd44c51b90df5498bfbdf1039a4c9

  </details>

**Issue Description:**

When typing a debugger command (`:command`) into the Swift REPL and pressing tab to autocomplete, the inserted autocompletion is missing the first autocompleted character.

 

For example, typing

``` java
:set<tab>
```

autocompletes to

``` java
:setings
```

(note the missing second t)

**Comment by poya** [comment]
<https://reviews.llvm.org/D82835>

**Comment by poya** [comment]
Fixed in swift/master with <https://github.com/apple/llvm-project/pull/1428>

Test in https://github.com/apple/llvm-project/pull/1421
