### ISSUE TITLE
[SR-12769] lldb expression command prints wrong result for characters in the range 0x80-0x9f

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4468]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12769      |
   |Radar             | None         |
   |Original Reporter | nsc (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 3cc9850b8c2873a9f96e0ffac540439c

  </details>

**duplicates**:  
* [SR-8111](https://bugs.swift.org/browse/SR-8111) Weird issue when printing String with unicode character  

**Issue Description:**

The expression command always prints "\u{c2}" for unprintable characters in the range "\u{80}"..."\u{9f}", e.g.:  
(lldb) expression "\u{85}"  
(String) $R1 = "\u{c2}"

It looks as though the buffer it tries to print is utf-8 encoded and it just grabs the first byte.

**Comment by poya** [comment]
Duplicate of SR-8111
