### ISSUE TITLE
[SR-12518] Couldn't lookup symbols error when using default function argument in REPL.

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4472]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12518      |
   |Radar             | rdar://problem/62201694         |
   |Original Reporter | palle (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)  
macOS 10.15.4 (19E266)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: e7ef19902d0508f1ace6b90b468f4cb3

  </details>

**Issue Description:**

It is not possible to declare a function with a default argument and then call it without providing a value for the default argument in the REPL. Doing so will result in a symbol lookup error for the default argument.

Minimal example:

``` java
$ swift
Welcome to Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29).
Type :help for assistance.
  1> func foo(bar: Int = 42) { 
  2.     print(bar) 
  3. } 
  4> foo()
error: Couldn't lookup symbols:
  default argument 0 of __lldb_expr_1.foo(bar: Swift.Int) -> ()
```

**Comment by beccadax** [comment]
@swift-ci create
