### ISSUE TITLE
[SR-11990] No error in REPL when importing non-existent module

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4474]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-11990      |
   |Radar             | rdar://problem/58455466         |
   |Original Reporter | rahulbhalley (JIRA User)      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Done    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164963588-b66cf8e5-c145-4891-a08f-5ca4dc3f9a99.gz)

      
<details>
  <summary>Environment</summary>

macOS Catalina 10.15.2 (19C57)

swift-tensorflow-DEVELOPMENT-2019-12-23-a.xctoolchain

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @augusto2112      |
   |Priority          | Medium      |

   

   md5: de6f1d92595ed53a3cd23cacecc0ffda

  </details>

**Issue Description:**

Importing a module in REPL even when it does not exists doesn't report any errors.

**Comment by beccadax** [comment]
@swift-ci create

**Comment by adrian-prantl** [comment]
Fixed by [Augusto Noronha](https://forums.swift.org/u/augusto2112) in <https://github.com/apple/llvm-project/pull/958.>
