### ISSUE TITLE
[SR-7973] LLDB can't find enum's associated values within switch

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4494]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-7973      |
   |Radar             | rdar://problem/41048339         |
   |Original Reporter | twof (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

Xcode 9.4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, LLDB for Swift    |
   |Labels            | Bug, DebugInfo        |
   |Assignee          | @vedantk      |
   |Priority          | Medium      |

   

   md5: 762758d965b1d4178c279d1c4886b8aa

  </details>

**Issue Description:**

Repro

``` java
enum Foo {
    case zero
    case one(String)
    case two(String)
}


let foo = Foo.one("hello")

switch foo {
case .zero:
    print("hello")
case .one(let hello), .two(let hello):
    print(hello) // (lldb) po hello
                 // error: <EXPR>:3:1: error: use of unresolved identifier 'hello'
                 // hello
                 // ^~~~~
}
```

**Comment by belkadan** [comment]
cc @adrian-prantl

**Comment by adrian-prantl** [comment]
@swift-ci create

**Comment by vedantk** [comment]
Addressed in <https://github.com/apple/swift/pull/32282.>
