### ISSUE TITLE
[SR-5994] Off by one error in URL description (swift REPL only)

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4505]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5994      |
   |Radar             | rdar://problem/29795062         |
   |Original Reporter | gwk (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

 $ uname -v

Darwin Kernel Version 17.0.0: Thu Aug 24 22:01:05 PDT 2017; root:xnu-4570.1.46\~3/RELEASE_X86_64

 

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @poya      |
   |Priority          | Medium      |

   

   md5: 2225b8215e13188ecbfd4009ead22a97

  </details>

**Issue Description:**

URL description and debugDescription appear fine, but the "f" in "file" is missing in the object description in the REPL.

 $ swift

Welcome to Apple Swift version 4.0 (swiftlang-900.0.63 clang-900.0.37). Type :help for assistance.

 1\> import Foundation 

  2\>  URL(fileURLWithPath: "a") 

$R0: URL = "a – ile:///Users/gwk/"

  3\>  URL(fileURLWithPath: "a").description

$R1: String = "a – file:///Users/gwk/"

  4\>  URL(fileURLWithPath: "a").debugDescription 

$R2: String = "a – file:///Users/gwk/"

**Comment by belkadan** [comment]
@swift-ci create

**Comment by keith** [comment]
You can also see this in lldb with just \`p URL(fileURLWithPath: "a")\`

**Comment by poya** [comment]
Fixed with https://github.com/apple/llvm-project/pull/378
