### ISSUE TITLE
[SR-3182] [master-next] macOS CI failure on most python tests

### ISSUE THREAD

**Issue by a0332500-857b-4d6a-874e-50b63b66b387** [swiftlang/llvm-project#4506]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-3182      |
   |Radar             | rdar://problem/29230692         |
   |Original Reporter | @trfiala      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Invalid    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @dcci      |
   |Priority          | Medium      |

   

   md5: 4f3b1961a57a52d6c24b3b5c7694c952

  </details>

**Issue Description:**

After the most recent merge of swift-lldb/upstream into swift-lldb/master-next, the macOS CI on ci.swift.org seem to be failing to run a very large number of the tests:

<https://ci.swift.org/view/swift-master-next/job/oss-lldb-incremental-osx-master-next/154/>

1500+ tests are failing.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
I have tried building and running both the CI way (i.e. the Swift build-script-driven build) and with the Xcode-driven build. In both cases, I have not yet been able to reproduce these failures.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Greg and I tracked down what's going on. The CI is exposing a bug that doesn't happen on LLDB developer systems. The Swift CI is using the system's Xcode-provided, Apple-signed debugserver and copying it into the just-build LLDB.framework. Thus, the new lldb client just built by the CI uses a privileged debugserver that is slightly older. This is always supposed to work, as we are frequently in a state where a new LLDB in Xcode needs to debug against older devices with older debugserver builds on them. So, this needs to work.

But, this is currently broken. The newer lldb in master-next is receiving no shared library info for whatever reason (i.e. likely a protocol compatibility breakage), and so no breakpoints are getting hit. This is the root cause of massive test failure on the macOS CI.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
This is ancient history.
