### ISSUE TITLE
[SR-2818] "open" visibility ignored in REPL

### ISSUE THREAD

**Issue by NachoSoto** [swiftlang/llvm-project#4510]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2818      |
   |Radar             | None         |
   |Original Reporter | @NachoSoto      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961648-30f63011-fc65-4e90-af17-afca1f047dff.gz)

      
<details>
  <summary>Environment</summary>

Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38) (from Xcode 8).

Swift version 4.0 (swiftlang-900.0.59 clang-900.0.34.2) (Xcode 9 beta)

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 2         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 0789d32abe52116b5760b1ac4e4aecbf

  </details>

**Issue Description:**

#### Description:

Enter the following code (as 2 separate expressions) on the Swift REPL:

    1> open class A {}
    2> class B: A {}

#### Expected result

This compiles (and additionally, \`open\` shouldn't even be required, as all expressions in the REPL, I imagine, should be in the same "module").

#### Actual result

This error:

    error: repl.swift:2:7: error: cannot inherit from non-open class 'A' outside of its defining module
    class B: A {}
          ^

**Comment by belkadan** [comment]
granataenrico (JIRA User), I seem to remember LLDB implicitly setting things to `public` in the past. Should that be `open` now, where applicable? (Unfortunately, we can't just splatter 'open' over everything.)

We could also consider cheating: make everything in LLDB files "compiled for testing" and then use testable imports for the previous-line modules.

**Comment by NachoSoto** [comment]
This is still broken.... 🙁 I guess nobody cares about the CLI.

**Comment by NachoSoto** [comment]
Still broken in Swift 4.0.

**Comment by slavapestov** [comment]
<https://github.com/apple/swift-lldb/pull/244>
