### ISSUE TITLE
[SR-2029] LLDB cannot print anonymous arguments if it stops in a closure

### ISSUE THREAD

**Issue by karwa** [swiftlang/llvm-project#4516]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2029      |
   |Radar             | rdar://problem/20719448         |
   |Original Reporter | @karwa      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

Swift 72802617d486ec272569d4ad1afb8afa588ed20a  
LLDB e67c7f4818d23b6f0f1bd6d5cf7e1ce1890b03e6

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 4         |
   |Component/s       | Compiler, LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @dcci      |
   |Priority          | Medium      |

   

   md5: f19f16dad253dbd568dc5291b4862a84

  </details>

**Issue Description:**

If LLDB stops in a closure (or maybe traps somewhere lower down the stack from a closure) with anonymous arguments, those arguments won't be printable even though they are visible in the "frame variable" view and in Xcode's frame variable view.

``` java
(lldb) fr variable
(Index, Index) $0 = {
  0 = {
    _base = (_position = 0)
    _countUTF16 = 1
  }
  1 = {
    _base = (_position = 50)
    _countUTF16 = 1
  }
}
(String) string = "..."
(lldb) po $0.0
error: <EXPR>:3:1: error: anonymous closure argument not contained in a closure
$0.0
^
```

The line in question was of the form:

zip(a, b).map { $0.function($1) }

And then there was a fatal error somewhere inside of $0.function().

**Comment by belkadan** [comment]
I think this is a check in the compiler, so it might be as simple as allowing that name in debugger mode. But there might also be parts of the compiler that assume that any identifier of this form must be a closure parameter.

**Comment by belkadan** [comment]
@swift-ci create

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
This was fixed here:  
<https://github.com/apple/swift-lldb/pull/964>
