### ISSUE TITLE
[SR-1995] Backspace can't clear the input character at linux REPL cmd line

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4518]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1995      |
   |Radar             | None         |
   |Original Reporter | skyslee2005 (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

Fedora 24  
Linux localhost 4.6.3-300.fc24.x86_64 \#1 SMP Fri Jun 24 20:52:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Arch Linux

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, Linux        |
   |Assignee          | @augusto2112      |
   |Priority          | Medium      |

   

   md5: cd8725d2f4789af2a61e7e93ddeae3ee

  </details>

**Issue Description:**

Bug occurs on fedora 24 after building swift from source with <https://github.com/thawkins/fedora-swift> And on Arch Linux when building from source with <https://github.com/RLovelett/swift-aur.>

Text can be deleted as intended until you enter any text and hit return then each character can only be replaced or deleted by going through repl history.  
1\> let a=3  
a: Int = 3  
2\>  
input any thing at 2\> ,then it will can't be cleared by Backspace(still showing)

**Comment by augusto2112** [comment]
Duplicate of <https://bugs.swift.org/browse/SR-15369.>

I'm marking these as dups so we can concentrate the discussion on a single issue. It has been fixed on main for a while, but unfortunately i missed the window to cherry-pick it into 5.5. If you're able to, please download the main snapshot on [https://www.swift.org/download/,](https://www.swift.org/download/) verify if it's working for you and letting me know on the SR-15369.
