### ISSUE TITLE
[SR-1751] Debugger shows data not matching the type of a variable

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4520]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1751      |
   |Radar             | None         |
   |Original Reporter | nameghino (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961418-f7e5a22e-08f9-403d-80b1-81e53ba3cd3f.gz)

      
<details>
  <summary>Environment</summary>

Version 7.3.1 (7D1014), swiftlang-2.2, lldb-350.0.21.9

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 38e2ee1eb1c8ecb53f5b08a8f0979004

  </details>

**duplicates**:  
* [SR-1007](https://bugs.swift.org/browse/SR-1007) Unsigned integer types have incorrect max values  

**Issue Description:**

I've discovered that the debugger is presenting negative numbers in a \`UInt8\` array, which could not be possible.

I cannot share the data that made this issue come up, but this is what I'm doing:

``` java
                let count = data.length / sizeof(UInt8)
                
                // create an array of Uint8
                var array = [UInt8](count: count, repeatedValue: 0)
                
                // copy bytes into array
                data.getBytes(&array, length:count * sizeof(UInt8))
```

The \`data\` parameter is an NSData that contains a sequence of \`UInt8\` values in binary form, and this same code parses a similar file (but of type \`Float\`) without any issues.

I'm attaching a screenshot of the Xcode debugger showing the contents of the \`data\` array.

**Comment by belkadan** [comment]
granataenrico (JIRA User), this is fixed in Swift 3, right?

**Comment by belkadan** [comment]
Ah, found it.
