### ISSUE TITLE
[SR-1138] Unsigned types display as signed in REPL (UInt8, UInt16, UInt32, UInt64)

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4527]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1138      |
   |Radar             | None         |
   |Original Reporter | jd20 (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

OSX 10.11.4 (15E65), Swift 2.2

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2d2afd2d1c9e64fbafa900f1e21ac285

  </details>

**duplicates**:  
* [SR-1007](https://bugs.swift.org/browse/SR-1007) Unsigned integer types have incorrect max values  

**Issue Description:**

When the REPL evaluates unsigned values, they display as if they were signed. print() shows the correct unsigned value however. Probably related to: <https://bugs.swift.org/browse/SR-1007>

Example:  
1\> var x: UInt8 = 150  
x: UInt8 = -106  
2\> print❌  
150  
3\> var y: UInt16 = 50000  
y: UInt16 = -15536  
4\> var z: UInt32 = 3000000000  
z: UInt32 = -1294967296

**Comment by belkadan** [comment]
Yep, should be fixed in master.
