### ISSUE TITLE
[SR-782] TestNSError.py is failing

### ISSUE THREAD

**Issue by a0332500-857b-4d6a-874e-50b63b66b387** [swiftlang/llvm-project#4542]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-782      |
   |Radar             | None         |
   |Original Reporter | @trfiala      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @lorentey      |
   |Priority          | Medium      |

   

   md5: 2581d7a4d16682e55b23488b52bc28f1

  </details>

**Issue Description:**

This will show up as soon as the merge from llvm.org lldb svn trunk gets submitted. I have it marked XFAIL, using this bug number to track.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Assigning to me until I figure out who to put it on. Seems likely Enrico Granata.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Karoy fixed this, closing.
