### ISSUE TITLE
[SR-760] GetSwiftTypeInfo() on non-legal SIL type not special cased. Name: (Swift.String, () throws -> ()) - Kind: 12

### ISSUE THREAD

**Issue by drewcrawford** [swiftlang/llvm-project#4546]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-760      |
   |Radar             | None         |
   |Original Reporter | @drewcrawford      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Cannot Reproduce    |
        
<details>
  <summary>Environment</summary>

Linux x64  
swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | granataenrico (JIRA)      |
   |Priority          | Medium      |

   

   md5: bbf985b80a6003b1b6eb2365881ddfd4

  </details>

**Issue Description:**

When asking for a backtrace from lldb during an XCTest run, I get the weird print in the title.

1\. Compile an XCTest target with e.g. SwiftPM. Or any method, really.  
2. Run the compiled target with lldb:

``` java
lldb path/to/xctesttarget
(lldb) r
```

3\. Convince lldb to stop during a test (by the test invoking fatalError or similar)  
4. Ask for a backtrace:

``` java
(lldb) bt
GetSwiftTypeInfo() on non-legal SIL type not special cased. Name: (Swift.String, () throws -> ()) - Kind: 12
GetSwiftTypeInfo() on non-legal SIL type not special cased. Name: (Swift.String, () throws -> ()) - Kind: 12
GetSwiftTypeInfo() on non-legal SIL type not special cased. Name: (Swift.String, () throws -> ()) - Kind: 12
GetSwiftTypeInfo() on non-legal SIL type not special cased. Name: (Swift.String, () throws -> ()) - Kind: 12
GetSwiftTypeInfo() on non-legal SIL type not special cased. Name: (Swift.String, () throws -> ()) - Kind: 12
GetSwiftTypeInfo() on non-legal SIL type not special cased. Name: (Swift.String, () throws -> ()) - Kind: 12
```

Anecdotally, this behavior seems correlated with lldb segfaulting occasionally. Not sure if related.

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
This doesn't seem to reproduce anymore.  
Feel free to reopen if you have away of reproducing this.
