### ISSUE TITLE
[SR-402] Assertion failed: (false && "GetMax64 unhandled case!"), function GetMaxU64, file /Users/buildnode/jenkins/workspace/oss-swift-package-osx/lldb/source/Core/DataExtractor.cpp, line 698.

### ISSUE THREAD

**Issue by norio-nomura** [swiftlang/llvm-project#4549]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-402      |
   |Radar             | None         |
   |Original Reporter | @norio-nomura      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Cannot Reproduce    |
        

Attachment: [Download](https://user-images.githubusercontent.com/2727770/164961093-5a2628cc-8384-4592-b578-1215afeb419b.gz)

      
<details>
  <summary>Environment</summary>

OS X 10.11.2 (15C50), Xcode 7.2 (7C68), swift-2.2-SNAPSHOT-2015-12-22-a-osx.pkg, swift-2.2-SNAPSHOT-2015-12-22-a-osx-symbols.pkg

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | granataenrico (JIRA)      |
   |Priority          | Medium      |

   

   md5: d702462b6a8268a15ff54d23d4deba29

  </details>

**Issue Description:**

Reproducing steps:  
1. Install swift-2.2-SNAPSHOT-2015-12-22-a-osx.pkg  
2. Install swift-2.2-SNAPSHOT-2015-12-22-a-osx-symbols.pkg  
3. Run \`sudo codesign -f --deep -s "Developer ID Application: Norio Nomura" /Library/Developer/Toolchains/swift-2.2-SNAPSHOT-2015-12-22-a.xctoolchain\`  
4. Run \`echo "settings set target.source-map /Users/buildnode/jenkins/workspace/oss-swift-package-osx /path/to/SWIFT_SOURCE_ROOT"\> \~/.lldbinit\`  
5. Run \`yes\|xcrun launch-with-toolchain /Library/Developer/Toolchains/swift-latest.xctoolchain\`  
6. Extract attached lldb-test.zip and open lldb-test.xcodeproj by Xcode  
7. Select Product\>Run menu  
8. Hit the breakpoint at \`Swift.print\`  
9. Show \`Variables View\` cause the crash

**Comment by Dante-Broggi** [comment]
Has this been resolved and is it no longer relevant? If either, it should be closed.

**Comment by norio-nomura** [comment]
closing this since I do not have an environment that can be reproduced anymore.
