### ISSUE TITLE
[SR-2126] In REPL, cannot redefine type with self-referential static property type.  Results in ambiguous type lookup.

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4591]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-2126      |
   |Radar             | None         |
   |Original Reporter | joshstaiger (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

XCode Version 8.0 beta 3 (8S174q)

OS X El Capitan 10.11.6 (15G31)

Apple Swift version 3.0 (swiftlang-800.0.34.6 clang-800.0.33)  
Target: x86_64-apple-macosx10.9  
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/lldb "--repl=-target x86_64-apple-macosx10.9 -enable-objc-interop -sdk /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -color-diagnostics"

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug, REPL        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: acd2598af7d326f8ee55d50ea46129f4

  </details>

**relates to**:  
* [SR-2127](https://bugs.swift.org/browse/SR-2127) In REPL, cannot redefine variable when using multi-line input.  

**Issue Description:**

Reproduce:

1\. Launch swift repl (Swift 3.0).  
2. Type:

``` java
struct S {
  static let x: S? = nil
}
```

3\. Hit enter. The S type is defined as expected.  
4. Re=enter the same code again:

``` java
struct S {
  static let x: S? = nil
}
```

5\. Hit enter. This results in the error:

    error: repl.swift:5:17: error: 'S' is ambiguous for type lookup in this context
      static let x: S? = nil
                    ^

    repl.swift:4:8: note: found this candidate
    struct S {

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
Fixed at some point.

``` java
% ../../lldb-macosx-x86_64/bin/lldb --repl
Welcome to Swift version 5.1-dev (LLVM 200186e28b, Swift a8dc4be076).
Type :help for assistance.
  1> struct S { 
  2.   static let x: S? = nil 
  3. }
  4> struct S { 
  5.   static let x: S? = nil 
  6. }
  7> struct S { 
  8.   static let x: S? = nil 
  9. }
```
