### ISSUE TITLE
[SR-61] REPL crash on tab completion

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4595]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-61      |
   |Radar             | None         |
   |Original Reporter | nitingupta (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Cannot Reproduce    |
        
<details>
  <summary>Environment</summary>

Ubuntu 15.10

swift built with preset=buildbot_linux_1510

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | jingham@apple.com (JIRA)      |
   |Priority          | Medium      |

   

   md5: 53c7f046be30d6711d39c698b7ababc9

  </details>

**is duplicated by**:  
* [SR-147](https://bugs.swift.org/browse/SR-147) REPL crash on Linux  

**Issue Description:**

in REPL:  
for c in "hello".\<TAB\>  
causes a crash  
-----

Welcome to Swift version 2.2-dev (LLVM 46be9ff861, Clang 4deb154edc, Swift 408d205ebb). Type :help for assistance.  
1\> for c in "hello".lldb: /home/ngupta/src/swift/swift/lib/Sema/TypeCheckConstraints.cpp:1246: Optional\<swift::Type\> swift::TypeChecker::getTypeOfExpressionWithoutApplying(swift::Expr \*&, swift::DeclContext \*, swift::FreeTypeVariableBinding, swift::ExprTypeCheckListener \*): Assertion \`exprType && !exprType-\>is\<ErrorType\>() && "erroneous solution?"' failed.  
Aborted (core dumped)

**Comment by Dante-Broggi** [comment]
Has this been resolved? If so, it should be marked as such.

**Comment by adrian-prantl** [comment]
Please reopen if this is still an issue.
