### ISSUE TITLE
[SR-10330] 100% reproducible debugger crash

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4597]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10330      |
   |Radar             | None         |
   |Original Reporter | GarthSnyder (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
<details>
  <summary>Environment</summary>

Mojave 10.14.4 (release)

Xcode 10.2 (release)

Swift 5

 

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @adrian-prantl      |
   |Priority          | Medium      |

   

   md5: b36c5f50fa1405e8654d8692000d81ca

  </details>

**Issue Description:**

This is reproducible for me on both macOS and iOS (simulator; I haven't tried a real device). I'm using Xcode, so it's possible the fault actually lies there.

Enter this code:

 

``` java
import Foundation

protocol HasResultType {
    associatedtype ResultType
}
 
extension HasResultType {
 
    static func fetch() throws -> [ResultType] {
        print("in fetch")
        return []
    }
    static func callFetch() throws {
        print("in callFetch")
        let results = try fetch() // Warns: results not used
    }    
}

class Entity: HasResultType {
    typealias ResultType = Entity
}

try? Entity.callFetch()
print("all done")
```

  

Then set a breakpoint on any line of callFetch() and run under the debugger. Here's the output I get:

  

``` java
in callFetch
Message from debugger: The LLDB RPC server has crashed. The crash log is located in ~/Library/Logs/DiagnosticReports and has a prefix 'lldb-rpc-server'. Please file a bug and attach the most recent crash log.
in fetch
all done
Program ended with exit code: -1
```

 

Don't worry about the original intent of the code; this version is so minified that you won't be able to tell. The remaining elements all seem to be necessary to reproduce the crash. In particular, the functions must be throwing and fetch() must return a value.

Contrary to the error message, no log is left in \~/Library/Logs/DiagnosticReports. In fact, there is no file starting with 'lldb-' anywhere under \~/Library except in \~/Library/Application Support/CrashReporter. That one contains no detail; it just reports that the crash occurred.

**Comment by compnerd** [comment]
CC: @dcci @adrian-prantl

**Comment by adrian-prantl** [comment]
I cloned this to rdar://problem/49699757.

**Comment by adrian-prantl** [comment]
I can reproduce the crash with Xcode 10.2 and I can't any more with a current Swift-5.1 toolchain.
