### ISSUE TITLE
[SR-9628] For loop with optional output variable causes infinite loop

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4612]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9628      |
   |Radar             | None         |
   |Original Reporter | spamsencer (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Duplicate    |
        
<details>
  <summary>Environment</summary>

macOS 10.14.2 (18C54)

Xcode 10.1 (10B61)

Swift 4.2

iOS 12.1

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Compiler, LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7d00dc923db09215081ba8df4e706d89

  </details>

**duplicates**:  
* [SR-8688](https://bugs.swift.org/browse/SR-8688) Infinite loop of for-in  

**Issue Description:**

Creating a For Loop and designating the output variable type as an optional causes the loop to repeat infinitely, without warning, blocking whatever thread from which it is being executed. The following is an example of such a loop:

``` java
// Infinite Loop Example
let solarSystemArray = ["Mercury", "Venus", "Earth", "Mars"]
for planet: String? in solarSystemArray {
    print(planet? ?? "Unknown planet")
    // Repeats infinitely
}

// Normal Loop Example
let solarSystemArray = ["Mercury", "Venus", "Earth", "Mars"]
for planet: String in solarSystemArray {
 print(planet)
 // Executes as expected
}
```

This issue was particularly difficult to spot at first, as neither the compiler nor the run-time flagged this as an issue. At the very least, the Swift compiler should supply an infinite loop warning when this type of code is written.

**Comment by lorentey** [comment]
This is the same issue as SR-8688.
