### ISSUE TITLE
[SR-5484] Unknown Console Debugger Error

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/llvm-project#4627]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-5484      |
   |Radar             | None         |
   |Original Reporter | eliwhittle (JIRA User)      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Invalid    |
        
<details>
  <summary>Environment</summary>

Swift 4

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: ee4b29040fcddcaffa7dd8028f9dc413

  </details>

**Issue Description:**

Console will randomly print

MyApp\[28845:2629358\] API error: (null) returned 0 width, assuming UIViewNoIntrinsicMetric

It is triggered randomly throughout the display of SFSafariViewController, it appears several times and it is not clear what is causing it. I have used breakpoints in all of the delegate methods of the SFSafariViewController, however this debugging message has been random.

**Comment by belkadan** [comment]
This is an error with an Apple API, not with Swift or LLDB. Please file any bug reports at <https://bugreport.apple.com/.>
