### ISSUE TITLE
Replacing RHS of an instruction with an instruction in LLVM

### ISSUE THREAD

**Issue by Montana** [swiftlang/llvm-project#4685]
Lets say suppose, I have the following instruction:

```c
%add = add nsw i32 %argc, 50
```

I would like at first, create a Binary instruction something like below:

```c%T1 = add nsw i32 %argc, 50
%add = add nsw i32 %argc, 50
```

And then somehow replace %add's instruction with an assignment to T1 as below:

```c
%add = %T1 //psuedo code
```

Need some suggestions on how to implement `"%add = %T1"`. 

I'm aware there is no assignment operator in LLVM IR so I can't write that as-is, so in theory, `%name = add i32 %this`, `%that` is a single instruction, a single llvm::Instruction* in memory. If I were to call `I->getName()` on that instruction would I get the name, "name"?

**Comment by hyp** [comment]
Hi @Montana . The issues in this repository are only related to the downstream changes in Apple's fork of llvm-project (clang/LLDB). It looks like this issue should go to the upstream GitHub.com/llvm/llvm-project repository.
