### ISSUE TITLE
LICENSE.TXT causes error while checking out repo on case-insensitive file system

### ISSUE THREAD

**Issue by StoneSpb** [swiftlang/llvm-project#5203]
After merging https://github.com/apple/llvm-project/commit/991cfd1379f7d5184a3f6306ac10cabec742bbd2 there are two license files in the repo: LICENSE.TXT and LICENSE.txt

When updating dependencies for swift development using `utils/update-checkout` script, first step seems to be cloning the `llvm-project` repo on default branch (`next`), then checking out desired branch/tag.
After cloning on case-insensitive file system (MacOS has the one by default) you can get a deleted file in your repo:
```
Cloning into 'llvm-project'...
Updating files:   3% (4732/121968)
...
Updating files: 100% (121968/121968), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'LICENSE.TXT'
  'LICENSE.txt'
```

This causes the subsequent checkout operation to fail.

**Comment by benlangmuir** [comment]
Fixed by ecddb8ca13088814332e6714da7de5eab45ace27
