### ISSUE TITLE
Opaque Pointers Support For Clang

### ISSUE THREAD

**Issue by thekief** [swiftlang/llvm-project#6326]
Currently the variable `CLANG_ENABLE_OPAQUE_POINTER` is never set to true, disabling clang's support for opaque pointers. I tried to rebuild a custom toolchain with it set to true but the compilation stops due to an error that seems to be related to ARM's pointer authentication on my M1 Mac.

Is there any plan for the near future to enable this feature officaially? Besides being more similar to the settings of the normal LLVM, the opaque pointers will soon be a requirement, deprecating the typed pointers.

**Comment by thekief** [comment]
In a commit last May [1] this feature has been disabled. Which rebranch would need to be stabilised?

[1] https://github.com/apple/llvm-project/commit/95b270ce18c919bf2b97689c54d475a6933dba7a

**Comment by thekief** [comment]
@bnbarham could you maybe shed some light on this?

**Comment by bnbarham** [comment]
This is only disabled in clang on stable/20220421 - stable/20221013 has it enabled by default (it doesn't have the option any more, just like upstream).

**Comment by thekief** [comment]
Good point. I did not properly look into the stable branches yet, because I am working with the Swift 5.8 release branch. Any chance it will be enabled there as well?

**Comment by bnbarham** [comment]
No, swift main is still on stable/20220421 and release/5.8 will definitely remain on it. main is switching over to stable/20221013 this week though - https://forums.swift.org/t/updating-llvm-project-branch-for-swift-main/63460.

**Comment by thekief** [comment]
Alright, I suppose Swift 5.9 will be the earliest release to support it then. Thank you for all the information.
