### ISSUE TITLE
How do I build the `llvm-cov` tool?

### ISSUE THREAD

**Issue by bachand** [swiftlang/llvm-project#6846]
Hi, I am working with my team to debug an issue with `llvm-cov` that we are seeing in the Xcode 14.3 release.

My understanding is the LLVM tools in the Xcode 14.3 release are built with [this branch](https://github.com/apple/llvm-project/tree/swift/release/5.8).

I am having trouble figuring out how to build the `llvm-cov` tool. The latest command that I've tried is below. This command completed succesfully but I don't see an `llvm-cov` binary in the ./build/ directory.

```bash
cmake -S llvm -B build -G Xcode -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt"
```

Any guidance on how to build the `llvm-cov` tool locally would be super appreciated!

**Comment by bachand** [comment]
@felipepiovezan I see a commit from you on the Swift 5.8 release branch. I was wondering if you would be able to help us at Airbnb with the above ^ question. Thanks!

**Comment by shepting** [comment]
I'm guessing that @kastiglione might know?

**Comment by kastiglione** [comment]
👋 After running CMake, open `build/LLVM.xcodeproj`. The freshly generated project starts with no schemes – you will be prompted to either automatically create schemes or create one or more schemes manually (which is how I do it). If you manually create a scheme, you can select the `llvm-cov` target. Then, building that scheme will build only that target, which saves you time, and none of the many other targets. Of course you can have your scheme build as many targets as you'd like.

**Comment by bachand** [comment]
Thank you @kastiglione . This unblocked us! 🙏

**Comment by keith** [comment]
another option is to not use Xcode and rely on the compile_commands.json file to integrate with the clangd lsp. If you do that you can generate the build files using the standard instructions and then run `ninja llvm-cov`. and run `./bin/llvm-lit ../llvm/test/tools/llvm-cov` to test any changes
