### ISSUE TITLE
xros and visionos compilation support?

### ISSUE THREAD

**Issue by bcardarella** [swiftlang/llvm-project#7595]
Rust requires upstream support for `visionos` to compile for Vision Pro. Are there plans to add?

https://github.com/rust-lang/compiler-team/issues/642#issuecomment-1701401208

**Comment by rudyrichter** [comment]
my team at 1Password requests this as well.

**Comment by sbogolepov** [comment]
Kotlin is on the same boat as Rust. Open-sourcing LLVM support for xrOS would be great.

**Comment by phatblat** [comment]
@bcardarella I believe this issue can be closed now. The issue you referenced is closed now.

**Comment by bcardarella** [comment]
@phatblat yes, agreed
