### ISSUE TITLE
[HELP]what's the exactly command to build Xcode toolchain from this apple repo?

### ISSUE THREAD

**Issue by renxuqiang** [swiftlang/llvm-project#8516]
from the [README.txt](https://github.com/apple/llvm-project/tree/next/clang/cmake/caches#readme) , it says :
Apple-stage1:

The Apple stage1 cache configures a two stage build similar to how Apple builds
the clang shipped with Xcode. The build files generated from this invocation has
a target named "stage2" which performs an LTO build of clang

but when i config the build like this:
cmake -G Ninja \
 -C ../clang/cmake/caches/Apple-stage1.cmake \
 -DCMAKE_INSTALL_PREFIX=~/toolchains \
 ../llvm

and then run:
ninja stage2
I got this error:
**ninja: error: unknown target 'stage2'**

did I miss something?
what command should i use to build the toolchain  that same with Xcode's build-in toolchain?

**Comment by MortadhaMannai** [comment]
When you encounter the error `ninja: error: unknown target 'stage2'`, it indicates that the build system (in this case, Ninja) cannot find a target named `stage2` in the build files generated by CMake.
To address this issue, you need to ensure that the target `stage2` is defined in the CMake configuration. This could involve checking the contents of the `Apple-stage1.cmake` cache file to see if it defines the `stage2` target. If it doesn't, you might need to modify the cache file or use a different one that includes the necessary targets.By following these steps and experimenting with different configurations, you should be able to build the LLVM/Clang toolchain with a configuration similar to Xcode's built-in toolchain.
