### ISSUE TITLE
Please backport d8352e93c1c8042d9166eab3d76d6c07ef585b6d

### ISSUE THREAD

**Issue by ADKaster** [swiftlang/llvm-project#8998]
I'm trying to use swift-shipped clang from `swfitly use 6.0-snapshot` to build https://github.com/ladybirdbrowser/ladybird , and I'm running into https://github.com/llvm/llvm-project/issues/53815

This issue was fixed for 18.x by https://github.com/llvm/llvm-project/commit/d8352e93c1c8042d9166eab3d76d6c07ef585b6d in upstream PR https://github.com/llvm/llvm-project/pull/83103

**Comment by DougGregor** [comment]
Merged the fix to the 6.0 release branch, thank you!
