### ISSUE TITLE
LLDB doesn't pass through language options to `ide::isSourceInputComplete`

### ISSUE THREAD

**Issue by hamishknight** [swiftlang/llvm-project#9430]
When checking for the end of the line in the REPL, LLDB calls into the compiler's `ide::isSourceInputComplete`, but doesn't pass along any language options so the compiler doesn't know if e.g bare slash regex is enabled, resulting in the issue reported by https://forums.swift.org/t/regex-compiler-vs-repl/75393. We ought to add a language option parameter and pass along the language options for the REPL's SwiftASTContext.

**Comment by Hachim-imane** [comment]
mport subprocess


wifi_data = (subprocess.check_output(["netsh", "wlan", "show", "profiles"]).decode("utf-8").split("\n"))


username = [i.split(":")[1][1:-1] for i in wifi_data if "All User" in i]


for i in username:
   show_pass = (subprocess.check_output(["netsh", "wlan", "show", "profile", i, "key=clear"]).decode("utf-8").split("\n"))
   show_pass = [b.split(":")[1][1:-1] for b in show_pass if "Key Content" in b]
   try:
       print("{:<30}|  {:<}".format(i, show_pass[0]))
   except IndexError:
       print("{:<30}|  {:<}".format(i, ""))
